### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by Osho1401** [matopeto/kindle-weather-dashboard#12]
Hello, first of all, thank you for your hard work.

I would like to report that i have problems with this mod since 4/5 days and wanted to ask if its not supported anymore.
When i go to kindle.hruncar.eu.... page it shows just a blank page. I upladed a picture where it can be seen.

Thanks in advance.

**Comment by matopeto** [comment]
@Osho1401 Hi it should be OK and it is still supported I am trying now and it is OK.

Here is link for prague: http://kindle.hrincar.eu/weather/index.html?city=Prague and it is working for me

It is not working on kindle or even not in browser?

If not in browser, can you please attatch direct link that not working?

**Comment by Osho1401** [comment]
It is not working on my kindle pw.
On mobile google chrome its working OK.

Here is direct link of a foto: 
https://www.photobox.co.uk/my/photo/full?photo_id=504635135984

**Comment by matopeto** [comment]
@Osho1401  link to the photobox photo not working for me.

I will look at it and fix next week. I don't have any kindle at home at the moment.

Five days ago I update moment.js library see: 7a44270e4a41a94e1c2ab2ca7f9506b95a752b1e, but not tried on real device after update. Maybe this is the problem.

**Comment by Osho1401** [comment]
https://postimg.cc/Lh5c0df8

here is a new link, i hope it works.

Yes 2 days after update i restarted my kindle and since than its not working.

The thing is, i was using this using this website: http://kindle.hrincar.eu/weather/ 
Without any mods to my kindle, so i dont know does it has any connections.
Thanks.

**Comment by N0VULK4** [comment]
Hello, first of all - I would like to thank you too.
 I`ve used code on my kindle4 - had same problem as Osho
moment-with-locales.js - replaced with old version and it is working

**Comment by matopeto** [comment]
Ok. Thank you for report. I will fix it no later than Tuesday

**Comment by matopeto** [comment]
@Osho1401 @N0VULK4 Hi, it is fixed and deployed now. It was error in moment.js library, see: https://github.com/moment/moment/pull/5995 for your interest.

**Comment by matopeto** [comment]
Reopening. It is working on PW but not on kindle 4.

**Comment by Osho1401** [comment]
I reseted my Kindle PW and tryed online version and its working again.
It also works on Kindle Oasis.
Thanks a lot.

**Comment by matopeto** [comment]
It is working on Kindle 4 too. Closing.

**Comment by jamfsam** [comment]
I am seeing this on my Kindle PW 7th Gen. Thanks for your hard work on this, it's the main thing my kindle is used for now!
