### ISSUE TITLE
Icons don't load on older browsers

### ISSUE THREAD

**Issue by andiohn** [matopeto/kindle-weather-dashboard#14]
Hello,
I don't want to be annoying but this software works great for a Nook Simple Touch too, it's just that the fonts just show question marks. I was wondering if there could be some fallbacks to pictures. Also, I was able to make a docker-compose for this and it works great! I'll paste it here:

version: '3.8'
services:
  php-apache-environment:
    container_name: eink-weather-dash
    image: php:8.0-apache
    volumes:
      - ./kindle-weather-dashboard:/var/www/html/
    networks:
      macvlan:
        ipv4_address: [IP-ADDRESS-HERE]

networks:
    macvlan:
      name: vmbr0macvlan
      driver: macvlan
      driver_opts:
        parent: vmbr0
      ipam:
        config:
          - subnet: [SUBNET]
            ip_range: [RANGE]
            gateway: [GATEWAY]

**Comment by matopeto** [comment]
Hi, sorry, i will do not do fallback to the pictures and don't have a nook to debug the problem also I don't have a time :( But feel free to fork and modify the source. I think it would not be very hard.

**Comment by andiohn** [comment]
Sounds good, I'll have to figure out how to do that. BTW, you can use that docker-compose file in the readme if you want.

**Comment by matopeto** [comment]
Thank you for the docker image sample. I will consider it to add to the docs. But now, I have no docker experiences and i don't want to add something that I don't understand and not tried by myself.

**Comment by andiohn** [comment]
No prob, the docker-compose file uses a php server configuration and runs a 'thin container' that only includes your software. 
I pass the volume with the php file to the server and give it an IP. That's basically it.
