### ISSUE TITLE
Add option for GMT+13 Time Zone

### ISSUE THREAD

**Issue by AngryKiwiNZ** [matopeto/kindle-weather-dashboard#15]
Hey Team, any chance you would consider adding GMT+13 timezone to allow for New Zealand (Daylight Time) zone to be used at http://kindle.hrincar.eu/weather/.

Thank you!

**Comment by matopeto** [comment]
Thanks for the report. Done.

**Comment by matopeto** [comment]
@AngryKiwiNZ i also added "auto" mode when timezone is determine by selected city/location.

**Comment by AngryKiwiNZ** [comment]
Thank you so much! I really appreciate the super quick change!

**Comment by AngryKiwiNZ** [comment]
> Thanks for the report. Done.

Thank you!
