### ISSUE TITLE
Instructions to disable screensaver in latest kindle firmware

### ISSUE THREAD

**Issue by fvillanustre** [matopeto/kindle-weather-dashboard#16]
~ds doesn't work anymore, but you can use the following instructions to disable screensaver in a non-jailbroken/non-rooted kindle with the latest firmware (in case you'd like to included them in your readme file):

1) Connect to your Kindle via USB
2) Create a file in the root directory called "TESTD_PREVENT_SCREENSAVER" - can be an empty file, but must be named exactly. (It'll ultimately sit in /mnt/us/ )
3) Reboot the device

**Comment by matopeto** [comment]
Thank you. I will check it and update the documentation.

**Comment by MichaelCyr** [comment]
What about 5.18.6
