### ISSUE TITLE
Website doesn't show any information

### ISSUE THREAD

**Issue by jise** [matopeto/kindle-weather-dashboard#27]
https://kindle.hrincar.eu/weather/index.html?city=Prague

![screencapture-kindle-hrincar-eu-weather-index-html-2024-08-12-21_02_51](https://github.com/user-attachments/assets/1bda14cf-e0b7-40cc-9523-123f6398b47d)

**Comment by jise** [comment]
When I git clone it locally and configure config.js, it works for me:

var api_locParams = "q=Rabyně";
var api_appId = "*********************";
var api_lang = "cz"

![screencapture-file-media-fuse-crostini-06d362fd761dbb538637c12d49cb84356ec97d6a-termina-penguin-kindle-weather-dashboard-index-html-2024-08-12-21_09_40](https://github.com/user-attachments/assets/41fbdd88-53f4-4aa9-bbf5-e04344c162d5)

**Comment by matopeto** [comment]
Hi @jise 

thanks for the report

the problem is that you access the "https" version and modern browsers then block the query because of "Blocked loading mixed active content", because the API runs on http

I will try to see if the old kindles support the "//" protocol, which would match the protocol being accessed

**Comment by jise** [comment]
There is something fishy with Chrome browser,  when I clicked the link for Prague from this your post
https://github.com/matopeto/kindle-weather-dashboard/issues/12#issuecomment-1099371737, Chrome show me https://kindle.hrincar.eu/weather/index.html?city=Prague instead of http://kindle.hrincar.eu/weather/index.html?city=Prague, I am sorry for false alarm, I didn't notice that URL change.

**Comment by matopeto** [comment]
I keep this issue open and i will try to fix the https version when I will have access to my old Kindle 4 to try it.
