### ISSUE TITLE
On Nook Simple Touch, Icons show as ???

### ISSUE THREAD

**Issue by andiohn** [matopeto/kindle-weather-dashboard#7]
I'm assuming it's because it's SSL store is out of date and cannot be updated. 

I wonder if the icons could be delivered in another way? Perhaps a 'fall back mode' option that uses some other method for icons?

I'm willing to test anything

**Comment by andiohn** [comment]
Perhaps not loading the css. I'm also going to share this software with the Nook Simple Touch XDA section, as there are a lot of Nooks that aren't being used right now since the SSL expiration.

**Comment by matopeto** [comment]
Hi, icons are made with custom font and it is stored localy, so if you run dashboard from kindle.hrincar.eu there is no SSL, it is http only site. Same with CSS.

I'am thinking that your nook maybe don't support custom fonts or some css property.

**Comment by andiohn** [comment]
Ya, probably it's the css property. I noticed the lack of SSL, which is why I was so excited! Thanks for the reply. I'm going to look into alternatives for the icons...

**Comment by matopeto** [comment]
Ok, i will close this issue as nook compatibility problem. Feel free to fork and update or send PR

**Comment by andiohn** [comment]
Sounds good! Thanks.
